### ISSUE TITLE
V2.0 Security Audit

### ISSUE THREAD

**Issue by defuse** [defuse/password-hashing#28]
Just before we release v2.0, after all of the other tickets in the milestone have been closed, it should be audited by me and some other volunteers. Maybe we can set up a bug bounty.

(Maybe @sarciszewski will be interested).

**Comment by defuse** [comment]
I'm really wondering, why, on August 16, 2014, that I thought all of the tickets would miraculously close that day.

**Comment by defuse** [comment]
Taylor from 2016 agrees with Taylor from 2015 and wonders why, on August 16, 2014, that I thought all of the tickets would miraculously close that day.

**Comment by defuse** [comment]
Dear Taylor from 2017: If this ticket still hasn't been closed, you need to re-evaluate your life choices.

**Comment by defuse** [comment]
As a part of this audit, go over the tests and make sure everything important is covered.

**Comment by defuse** [comment]
All the other 2.0 tickets are closed, so the audit may now commence (tomorrow)!

**Comment by defuse** [comment]
Check that we're not generating too much output with PBKDF2. There's that thing where if you ask for too much it does double the work with no benefit.

**Comment by defuse** [comment]
**CALL FOR CODE REVIEW:**

This code does PBKDF2-SHA1 password storage in PHP, Ruby, C#, and Java. The implementations are compatible with each other. Since we have better things now (bcrypt, scrypt, yescrypt, argon2, etc.) I'm ceasing development of this library and putting out the final version. **I'd like to not touch this code anymore, so now's the time to find all the security bugs!**

If you'd like to help, please try to find bugs in the [compatible-versions branch](https://github.com/defuse/password-hashing/tree/compatible-versions)! Open tickets if you find any.

Thanks!

**Comment by defuse** [comment]
**Taylor's Audit (4.5 hours):**

- [ ] Plan the audit (25min).
- [ ] PasswordStorage.cs (25min)
- [ ] PasswordStorage.php (25min)
- [ ] PasswordStorage.rb (25min)
- [ ] PasswordStorage.java (25min)
- [ ] C# tests are adequate. (25min)
- [ ] PHP tests are adequate. (25min)
- [ ] Ruby tests are adequate. (25min)
- [ ] Java tests are adequate. (25min)
- [ ] Cross-compatibility tests are adequate (25min).

**Comment by paragonie-scott** [comment]
#68 + #69 are worth looking at.

**Comment by defuse** [comment]
Okay, I'm satisfied by this code's review status! There's a few open issues and then this will finally be done!!!!
