### ISSUE TITLE
State of the PHP module in compatible branch

### ISSUE THREAD

**Issue by pocesar** [defuse/password-hashing#43]
Thanks for having the time to create something like this.

The PHP code in the compartible-versions can be used in production? Or should wait for the it to reach a certain tag? (although there are no tags right now)

**Comment by defuse** [comment]
If you need compatibility across languages, they should be safe to use. But the API might change, so if you don't need them to be compatible with each other I would recommend using the regular ones for now. (I have no idea when I'll get time to finish the compatible-versions branch).

**Comment by pocesar** [comment]
alright, not too worried about the API change, refactoring is easier than asking all your users to update their passwords :collision:
