### ISSUE TITLE
Javascript version

### ISSUE THREAD

**Issue by pocesar** [defuse/password-hashing#44]
Any plans to have this ported to Node.js? Should be pretty easy, it has all the requirements out of the box (that means, on npm)

If it's not already in the makings, I could try to hack something together

**Comment by redragonx** [comment]
We don't have plans for this yet. You could create one and we'll audit the code later.

**Comment by pocesar** [comment]
see #45

**Comment by defuse** [comment]
I also got another implementation sent to my email (Bill Walker; Feb 08, 2016). If we do want to support one (I dont think I'll have time), then I should take the best of both!

**Comment by defuse** [comment]
Closing this to indicate that I won't be doing it.
