### ISSUE TITLE
Close the current tickets then switch to "security maintenance mode."

### ISSUE THREAD

**Issue by defuse** [defuse/password-hashing#50]
This library uses PBKDF2. There are much better options now. I'm going to finish all of the currently-open tickets, and then "abandon" it. By abandon, I mean: No new features, only fixes to bugs (especially security bugs) reported by users.

The only case where you want to use this library is if you really *needed* compatibility between languages. Otherwise, there are better options.

**Comment by gentlesystems** [comment]
It would probably be a good idea to list some of these "much better options," both for current users and new potential users who are likely to continue looking for an implementation of the popular pbkdf2.  I suppose you're talking about things like scrypt?

**Comment by davisnw** [comment]
I agree with the sentiment of listing "much better options" - and it might be too much to ask, but a quick summary of why they are better would be appreciated.  Do you have any association with the folks at crackstation?  I originally found this library by following the links from https://crackstation.net/hashing-security.htm  Perhaps you could encourage them to update that article?

**Comment by defuse** [comment]
Great point. We should *definitely* make a list of the best options for (at least) all of the platforms this library supports. It would be terrible if we just said "don't use this" without giving any hints about what's better!

@gentlesystems: Yes, scrypt, and now the password hashing competition winner Argon2.
@davisnw: I wrote that article, yes it desperately needs an update.

**Comment by redragonx** [comment]
So you're gonna implement just security fixes?

**Comment by defuse** [comment]
@redragonx: Yes, and non-security bugfixes. No new features or supported languages.

**Comment by defuse** [comment]
To close this ticket: indicate the fact it's in "maintenance mode" in the readme.

**Comment by defuse** [comment]
Done!
