### ISSUE TITLE
Add "What should you use instead?" section to the README

### ISSUE THREAD

**Issue by defuse** [defuse/password-hashing#53]

**Comment by defuse** [comment]
Hey @paragonie-scott: I'm looking for one of two things:

1. A single blog post that explains how to store passwords in a bunch of different languages (including PHP, Ruby, C#, and Java), OR
2. A list of individual blog posts that explain how to store passwords, one for each language (at least PHP, Ruby, C#, and Java).

Ideally I'd like the blog post(s)'s authors to update them as technology changes, so that I just have to link to the post(s) and then I can forget about it, instead of maintaining instructions in the README myself.

Do you know any good resources like that? Maybe a topic for the paragonie blog?

**Comment by paragonie-scott** [comment]
I'll write one right now, and throw Node.js in for free.

(My cross-platform recommendation will be, of course, libsodium.)

**Comment by defuse** [comment]
@paragonie-scott: I just updated the README.md to mention libsodium for now (read your mind), let me know when you've got something else to point to and I'll add that in :)

**Comment by paragonie-scott** [comment]
It'll probably take an hour or two to write this out. ;)

**Comment by defuse** [comment]
Closing this ticket so I feel good that the ticket list is smaller. You can DM me on twitter or something when it's done :)
