### ISSUE TITLE
Python Implementation wanted?

### ISSUE THREAD

**Issue by murrple-1** [defuse/password-hashing#77]
Hey!

So, I have been using and loving the PHP version of this library (v1), but recently, we started a new project in Python, so I was seeking a Python implementation of the library. Naturally, I don't want to flood you with too many parallel implementations, but I was wondering if you are interested in a Python version of the code. If you are, I have an blind-copy (and naive - I don't claim to be trained in cryptography) implementation (see: https://gist.github.com/murrple-1/a34e89109014f6527aa2d434164c4776) that I would be willing to PR.

**Comment by defuse** [comment]
Hi! It's totally awesome that you ported it to python! It's too bad I don't really have the time available to maintain more versions, but you're welcome to maintain your own python clone in a repo of your own. One thing you could do to assure yourself that it's a good implementation would be to write tests that compare it to the ones in this repository!
