### ISSUE TITLE
Fields are missing from the password hash.

### ISSUE THREAD

**Issue by lezixb** [defuse/password-hashing#80]
I am trying to implement the C# version of the password hashing. But i get above exception, please can anybody help me resolve it. Thanks in advance.

**Comment by davidsekar** [comment]
A quick search for the mentioned error message in the Source would point you to the reason...

From error message, I guess that you have allocated less storage space / characters in the database column for storing the password. As a result, the the part of the hash value would have been truncated before saving...

This is the expected format/fields of the hash generated by the algorithm

> // format: algorithm:iterations:hashSize:salt:hash

So while verifying password, the code should have thrown that some part of above format  is missing exception.

Set at-least 75 characters in database for storing the Hash generated by this application (IF you are using the default settings provided in the algorithm)

**Comment by defuse** [comment]
@davidsekar: Thanks for answering! That is indeed likely what's happening.

**Comment by lezixb** [comment]
@davidsekar thanks i realized that my hash password was getting truncated because the database field was small. Thanks really grateful.
