### ISSUE TITLE
Broken SHA-1

### ISSUE THREAD

**Issue by Tanzy** [defuse/password-hashing#86]
How does this fit in with Google breaking SHA-1? We are using it and I need to reassure my boss that our password hashing is OK.

https://shattered.it/

**Comment by defuse** [comment]
Collision attacks on the hash function do not impact its security for password hashing. Formally, to break a password hash you need to find a preimage (recover the original password) or a second-preimage (find a different password that also matches the hash). So, the collision attacks on SHA-1 don't impact this library at all. 

If someone comes up with a practical way to find SHA-1 second-preimages, then we'll need to worry. Historically, cryptographers haven't been able to find preimage or second-preimage attacks even for trivially-collidable hash functions like MD4. So, it's unlikely practical second-preimage attacks will be found for SHA-1.

What someone using this library today should do is keep using it until a native implementation of one of the PHC finalists (Argon2, yescrypt, etc.) becomes available, and then switch to that.

**Comment by Tanzy** [comment]
Thanks for that, much appreciated :)
