### ISSUE TITLE
Upgrade mcrypt_create_iv to support PHP 7.2 (and add travis-ci tests for new PHP versions)

### ISSUE THREAD

**Issue by defuse** [defuse/password-hashing#92]
This is urgent, since some users are wanting to upgrade to 7.2.

**Comment by defuse** [comment]
Actually this has already been done!

**Comment by luckydonald** [comment]
I was looking at this as my IDE highlighted that `mcrypt_create_iv` function as depricated.
Maybe a comment above those functions along the lines of  `// PHP 7.2+` and `// Fallback for PHP < 7.2` could be added for immediate clarity?
